[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Sims-lab pipelines"
authors = [{name = "Kevin Rue-Albrecht", email = "kevin.rue-albrecht@imm.ox.ac.uk"}]
dynamic = ["version", "description"]
